### ISSUE TITLE
uuid are always parsed as big endian, not little endian

### ISSUE THREAD

**Issue by dannydulai** [zefferus/uuid-parse#2]
uuid are always parsed as big endian, not little endian

**Comment by PizzaBrandon** [comment]
I don't see this as a bug, but you're welcome to submit a PR for documentation updates.

**Comment by dannydulai** [comment]
Imagine you have a string uuid that was decoded on two platforms, such as .NET and NodeJS. The decoded representation will not match.

It's not a bug. It is a limitation that makes the library difficult to use. It is something the library would ideally allow you to optionally specify.
