### ISSUE TITLE
Not IE 11 compliant

### ISSUE THREAD

**Issue by xaviergxf** [zefferus/uuid-parse#3]
Hi zefferus,

   Unfortunately this code is not ES 2015 compliant. I'm having the following exception in IE 11:
SCRIPT1003: Expected ':'
on the following part:
module.exports = {
  parse,
  unparse
};

Can you modify your repo and release a new version with this correction? How about migrating to typescript?

Thanks,
Regards

**Comment by PizzaBrandon** [comment]
Object shorthand notation [_is_ defined in ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer). IE 11, on the other hand, [isn't broadly ES2015 compatible.](https://kangax.github.io/compat-table/es6/#ie11)

This module targets node. It is recommended that you use a converter such as webpack before deploying node modules to a browser environment.

**Comment by xaviergxf** [comment]
@PizzaBrandon do you have any examples for using with angular cli? Or event with just webpack? I know that Typescript can compile targeting ES2015 or others, but i don't know how javascript can be converted.

Thanks
